auxiliary_data_dir: /data/shared/climate-data/aux
input_files:
- /home/group6/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrepnap2rdo4_20260320_094617/preproc/diagnostic/pr/metadata.yml
- /home/group6/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrepnap2rdo4_20260320_094617/preproc/diagnostic/tas/metadata.yml
- /home/group6/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrepnap2rdo4_20260320_094617/preproc/diagnostic/rsds/metadata.yml
log_level: info
output_file_type: png
plot_dir: /home/group6/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrepnap2rdo4_20260320_094617/plots/diagnostic/script
recipe: ewcrepnap2rdo4.yml
run_dir: /home/group6/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrepnap2rdo4_20260320_094617/run/diagnostic/script
script: script
version: 2.11.1
work_dir: /home/group6/teaching-materials/book/2_modelling_advanced_ewatercycle/esmvaltool_output/ewcrepnap2rdo4_20260320_094617/work/diagnostic/script
