title: Teaching Material on Hydrological Modelling used in ENVM1502 course at Delft University of Technology
author: Teaching Material by Markus Hrachowitz (TU Delft). eWaterCycle platform by Rolf Hut (TU Delft), Bart Schilperoort (Netherlands eScience Center) and the bigger ewaterCycle team, including much work building the jupyter book by Anne Verslijen, Ahmed Farahat and Ezzat Qadriyeh. Jupyter book version uilt with <a href="https://teachbooks.tudelft.nl/">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a> #add your own name here
logo: figures/ewatercycle_logo.png #add your own logo here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/TB_favicon.ico"
  baseurl :  "https://github.com/eWaterCycle/teaching-materials/" 
  
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/eWaterCycle/teaching-materials/" 
      repository_branch: main
      path_to_docs: book
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        jupyterhub_url: https://ewatercycleenvm.ewatercycle-tud.src.surf-hosted.nl/jupyter
        notebook_interface: "jupyterlab"
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter

bibtex_bibfiles: 
  - references.bib
